name: AdventureWorks-CD

on:
  workflow_run:
    workflows: ["AdventureWorks-CI"]
    branches: [master]
    types:
      - completed
    
jobs:
  deploy-dacpac:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download DACPAC Artifact
      uses: actions/download-artifact@v2
      with:
        name: published-app
        
    - name: List files
      run: |
        dir

    - name: Deploy DACPAC to SQL Server
      run: |
        # Reemplaza estos valores con tus detalles de conexión
        $serverName = "tu_servidor.database.windows.net"
        $dbName = "tu_base_de_datos"
        $username = ${{ secrets.DB_USERNAME }}
        $password = ${{ secrets.DB_PASSWORD }}
        $dacpacFile = Get-ChildItem *.dacpac | Select-Object -ExpandProperty Name
        # Asegúrate de tener sqlpackage disponible en tu entorno de ejecución
        sqlpackage /Action:Publish /TargetServerName:$serverName /TargetDatabaseName:$dbName /TargetUser:$username /TargetPassword:$password /SourceFile:$dacpacFile /p:BlockOnPossibleDataLoss=false
