name: Build .NET Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: sql-monitor

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Especifica tu versión de .NET

    - name: Restore dependencies
      run: dotnet restore AdventureWorks.sln

    - name: Build
      run: dotnet build AdventureWorks.sln --configuration Release --output publish/

    - name: Zip Artifacts
      run: Compress-Archive -Path publish/* -DestinationPath publish.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
           name: published-app
           path: publish.zip
