name: Build .NET Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Especifica tu versión de .NET

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild AdventureWorks/AdventureWorks.csproj -t:rebuild -verbosity:diag -property:Configuration=Release


    - name: Zip Artifacts
      run: Compress-Archive -Path publish/* -DestinationPath publish.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
           name: published-app
           path: publish.zip
